### ISSUE TITLE
Bug: offset on value of type null

### ISSUE THREAD

**Issue by miloshavlicek** [janbarasek/doctrine-pro#3]
Error: In DocParser.php line 1002: Trying to access array offset on value of type null

There is a bug that is already fixed in an original package:
https://github.com/doctrine/annotations/blob/e9bff219976eb23204d470299274287603cff9b8/lib/Doctrine/Common/Annotations/DocParser.php#L1024

There should be `null !== $this->lexer->lookahead &&` in begin of the while loop condition.

I think that it would be better to use the original package as a dependency rather than fixing it each time a new version is released.

**Comment by janbarasek** [comment]
@miloshavlicek This version exists because I haven't been able to fix a bug in the main version of the library after a few months, which causes SmartObject to not work.

Source: https://github.com/doctrine/common/pull/869

**Comment by janbarasek** [comment]
Fixed in `2.13.2`: https://github.com/doctrine/common/releases
